version: '3.7'

services:
  web:
    image: dt
    build:
      context: ../src/web
      dockerfile: Dockerfile
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - ../coverage/:/usr/src/app/htmlcov/
    ports:
      - "80:8000"
    env_file:
      - ./.ci.env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.ci.env
    expose:
      - 5432

volumes:
  postgres_data:
